version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  postgres:
    image: library/postgres
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=soundcloud_analytics
  api:
    build: ./server
    environment:
      - ELASTICSEARCH_ADDRESS=elasticsearch
      - ELASTICSEARCH_INDEX=soundcloud-analytics
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_TYPE=user
      - LOGGING=true
      - POSTGRES_DATABASE=soundcloud_analytics
      - POSTGRES_HOST=postgres
      - POSTGRES_USERNAME=test
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT=5432
      - POSTGRES_TIMEZONE=America/Los_Angeles
      - SOUNDCLOUD_CLIENT_ID=bTdSYQ26Va0TlBtAjyE9lSxs4RPuIfze
      - SERVER_PORT=8000
    depends_on:
      - elasticsearch
      - postgres
  client:
    build: './client'
  web:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api
      - client
